[package]
name = "rustyclip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs = "0.0.5"
toml = "0.7.2"
x11 = "2.21.0"
x11-clipboard = "0.7.0"
